/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.46).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Scheduler;
import io.swagger.model.SchedulerInput;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-08-21T22:00:36.997790207Z[GMT]")
@Validated
public interface SchedulersApi {

    @Operation(summary = "Create a new scheduler", description = "", tags={ "schedulers" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Scheduler created", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Scheduler.class))),
        
        @ApiResponse(responseCode = "400", description = "Bad request") })
    @RequestMapping(value = "/schedulers",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Scheduler> createScheduler(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody SchedulerInput body);


    @Operation(summary = "Get a list of schedulers", description = "", tags={ "schedulers" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "List of schedulers", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Scheduler.class)))) })
    @RequestMapping(value = "/schedulers",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Scheduler>> getSchedulers();

}

